name: glutenvoid_app
description: "Desarrollo de una aplicación movil para usuarios con trastornos alimenticios provocados por el gluten"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.11
  http: ^1.0.0
  google_ml_kit: ^0.16.3
  image_picker: ^0.8.4+4
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  provider: ^6.1.2
  flutter_exit_app: ^1.0.0
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  collection: 1.18.0
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  carousel_slider: 4.2.1
  flip_card: 0.7.0



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: 3.0.0
  lints: 3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/gluten_void_icon.png"
  adaptive_icon_background: "#FFFFFF"



flutter:
  assets:
    - assets/images/gv_animated.gif
    - assets/images/gv_animated.mp4
    - assets/images/gluten_void_logo.png

  uses-material-design: true

